[gcp_service_account]
type = "service_account"
project_id = "urenregistratie-459719"
private_key_id = "154e70b90b9e66019cebc3ef46f26cd8c9690a7c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQC00/iLVT8KiMa5
FUj8UjtRcpJtEuMjvdzLXKjJGOB8u9WCAhHEfoHd9fIa7YwEPAUbykvPbUSOIQxX
vG0xxpZK2IqyfmtmMpaXrDajOmK9vNiwVAt9JZcfqMouTwag+WVKjpQK2ii8Mffz
MkSxCJivhPRYPxRpiSrqROM/8IYWLBbfUfK3oIzxKlmi4XplcHmxNfte7JLbHXcd
2z/yr+4HR9t0Xt8MWTVHcc6rlKwk32JVy+XQr6fZs2V2du+MrP0UX5Oz17uPnaN2
sn7LOuibdOslSj8dm9pHngGx5n6Fqlu5tWITFWZgs8T55GpKs5YPl6bPMeyDCRXR
HCzT+VeHAgMBAAECgf9pmWAL/jxSao2iiEuXDm6VodLg36bFuJq4J+Rpi52NOiP1
SEAX/8jXVkmMcCzUTDivgfPDrovadHJAykj6SH58NvjIRAt0IxbOfENsDyyaoS3p
yyrqaolWc7ueT4gPeZUtdRX/QGeJf6TM4Q48VEjWN056OlwxRWlKZfBP5qZnS1yZ
OddXtlRlpGWgXmg8o4JedCxyw1dCKCMyJ1+YtM3g9vgMNLqqyoxkHhI5KEkHuvIf
cMPI/ahpoVazKzistPeWCwJaCBauIfMn0Iz6zqQNR8IUqU8Fxz7yu0IFtlmd4JEL
NrIyJK+YWd8Xz1q9eu5pYxPvCe1j0vx3iafpuQUCgYEA3zGT6xCLffGmkSGbcY75
/aAtgt1jd9rzbuOjkSSIvffKdKyvXVfyqoN1zT/N0Bznxz/QruISFgsFpCYyClZL
9l1dOlJvvl8J1gKfbEUbdTM4MwKImV/u2cudxUwr/+9uRcCa7m9jmTs8Z0m1S2zi
5EAk0YCNQ8F8wCkSBv17OyMCgYEAz2g9tHwucvwjYwPQream3aikOVDXYSvVcqWZ
\K2FH5JIGpvkLgDWmYxGdCIsQehrG2CBzRfUG+m1vremDiCfyVdartgdvzAY+0T2u
i5kzyvrHvzknuR5Gp+jGhL0cUYBw2wgI6s3sOXlPLrGV8/ij4RX3j2ghC1bzSgcJ
FMxtGk0CgYEApH6Yov1doWPxPDOFqesTSh68jB94iMRA97AkQ/umIEQ43UbMNEJ2
Yb9jmfL1T/WNyWa5+bo6VC6paLKR3NZ/Q8LJzAsnuim3SRhDwPsp4nXubIHohQmU
MsaDr/6Uyxr+rb/nL+W+hReITCOhz0Yf7tNrj1BsTMyUkddzJt247fsCgYBN3KlF
h1T8r7EtK7J8hllgXz3/kly4yvbfilFdGrEdmsBKkLYDlKB5EpSsL2CpJkI9wrjj
q1/KRakmVcKeK7jrBqMBu/r5UeLlNE3BdGsgKVMxc2h5M2d9A4L7M+9cnWZAo9yN
IW8sCGF0exB7PX1wM4nzWTkGg8bjpI6BM1lGBQKBgBxzWAkIPZ6/dUx9ECzONgkO
Oje4eKUIqZX4r0nIt6kNdj0+KqKWn4i8ArCTklnZRLPGO5d2b5w3NWmRFJtitQjg
WUBSCYEDJrBZAejegc/oXIQYYW41HweiJlTo+vPUIzqONaTji5JKh5pRK9rXc2Wv
LipJH7L+vM4lsAqgiKSt
-----END PRIVATE KEY-----"""
client_email = "urenregistratie@urenregistratie-459719.iam.gserviceaccount.com"
client_id= "100721249694299392503"
auth_uri= "https://accounts.google.com/o/oauth2/auth"
token_uri= "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url= "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url= "https://www.googleapis.com/robot/v1/metadata/x509/urenregistratie%40urenregistratie-459719.iam.gserviceaccount.com"